name: Release

on:
  push:
    tags:
      - "v*.*.*"
    
permissions:
      contents: read
      
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - name: Make wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: publishAllPublicationsToSonatypeRepository --max-workers 1
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: '##Gradle \n```implementation("io.github.vincentvibe3:gqlclient:${{ env.RELEASE_VERSION }}")```'
