name: Release

on:
  push:
    tags:
      - "v*.*.*"
    
permissions:
  contents: write
      
jobs:
  create-staging-repository:
   name: Create staging repository
   runs-on: ubuntu-latest
   outputs:
     repository_id: ${{ steps.create.outputs.repository_id }}
   steps:
     - id: create
       uses: nexus-actions/create-nexus-staging-repo@v1.1
       with:
         username: ${{ secrets.OSSRH_USERNAME }}
         password: ${{ secrets.OSSRH_PASSWORD }}
         staging_profile_id: ${{ secrets.OSSRH_PROFILE_ID }}
         base_url: https://s01.oss.sonatype.org/service/local/
         
  build-publish:
    needs: create-staging-repository
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:    
    
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      
    - name: Make wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env: 
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY: ${{ secrets.SIGNING_SECRET_KEY }}
        STAGING_REPO_ID: ${{needs.create-staging-repository.outputs.repository_id}}
      with:
        arguments: publishAllPublicationsToSonatypeRepository --max-workers 1
        
  drop-or-release:
   needs: [create-staging-repository, build-publish]
   runs-on: ubuntu-latest
   if: ${{ always() && needs.create-staging-repository.result == 'success' }}
   steps:
    - uses: actions/checkout@v3
    - name: Discard
      if: ${{ needs.build-publish.result != 'success' }}
      uses: nexus-actions/drop-nexus-staging-repo@v1
      with:
       username: ${{ secrets.OSSRH_USERNAME }}
       password: ${{ secrets.OSSRH_PASSWORD }}
       staging_repository_id: ${{ needs.create-staging-repository.outputs.repository_id }}
       base_url: https://s01.oss.sonatype.org/service/local/
         
    - name: Release
      if: ${{ needs.build-publish.result == 'success' }}
      uses: nexus-actions/release-nexus-staging-repo@v1
      with:
         username: ${{ secrets.OSSRH_USERNAME }}
         password: ${{ secrets.OSSRH_PASSWORD }}
         staging_repository_id: ${{ needs.create-staging-repository.outputs.repository_id }}
         base_url: https://s01.oss.sonatype.org/service/local/
    
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Release
      if: ${{ needs.build-publish.result == 'success' }}
      uses: softprops/action-gh-release@v1
      with:
        body: | 
          ## Gradle 
          ```kotlin 
          implementation("io.github.vincentvibe3:gqlclient:${{ env.RELEASE_VERSION }}")
          ```
        
    - name: Status webhook  
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Release workflow"
        username: GitHub Actions
